
# -*- coding: utf-8 -*-
"""Remaining months 2023-07 .. 2026-09 for monthly DB."""
from __future__ import annotations

def extend(MONTHS, month_file, upd, ev, meme):
    # ===== 2023 H2 =====
    MONTHS["2023-07"] = month_file(
        "2023-07",
        "Claude 2 + Llama 2 — open commercial weights and long-context Claude",
        [upd("claude-2", "Claude 2 (Jul 11)", 5),
         upd("llama-2", "Llama 2 7B–70B commercial open (Jul 18)", 5),
         upd("chatgpt", "Code Interpreter broader rollout path", 3)],
        [ev("Claude 2", "Improved coding/reasoning; 100K context productization.",
            ["https://www.anthropic.com"], "2023-07-11"),
         ev("Llama 2", "Meta open weights for commercial use.",
            ["https://ai.meta.com/llama/"], "2023-07-18")],
        [meme("Llama 2 license", "Commercial-friendly open weights party"),
         meme("Claude 2 essays", "Writers migrate from GPT-4")],
        "Open-weights legitimacy + Claude writing fandom.",
        ["claude-2", "llama-2", "gpt-4", "chatgpt", "cursor", "github-copilot"],
    )
    MONTHS["2023-08"] = month_file(
        "2023-08",
        "Code Llama + Qwen-7B + CN public chatbot approvals + 豆包",
        [upd("code-llama", "Code Llama (Aug 24)", 4),
         upd("qwen", "Qwen-7B open weights (Aug 3)", 4),
         upd("ernie-bot", "Public China launch after approvals (Aug 31)", 5),
         upd("doubao", "ByteDance 豆包 launches (~Aug)", 4),
         upd("baichuan", "Baichuan-53B enterprise push", 3),
         upd("chatglm", "智谱清言 public with approval cohort", 4),
         upd("sensenova", "SenseChat public availability", 3),
         upd("minimax", "MiniMax public chatbot cohort", 3),
         upd("duet-ai", "Google Duet AI branding wave", 2)],
        [ev("China generative AI public licenses", "Baidu and peers open chatbots to general users.",
            ["https://www.reuters.com/technology/baidu-among-first-win-china-approval-ai-models-bloomberg-news-2023-08-30/"], "2023-08-31"),
         ev("Code Llama", "Meta coding specialist on Llama 2.",
            [], "2023-08-24")],
        [meme("备案过了", "CN approval meme storm"),
         meme("豆包入场", "ByteDance consumer AI")],
        "CN consumer AI apps go live at scale; coding open models surge.",
        ["ernie-bot", "doubao", "qwen", "code-llama", "chatglm", "baichuan", "minimax", "llama-2"],
    )
    MONTHS["2023-09"] = month_file(
        "2023-09",
        "Mistral 7B shock + DALL·E 3 + Meta AI + 混元",
        [upd("mistral-7b", "Mistral 7B Apache 2.0 (Sep 27)", 5),
         upd("dalle-3", "DALL·E 3 announced", 4),
         upd("meta-ai", "Meta AI assistant push", 3),
         upd("hunyuan", "Tencent 混元 public-facing push", 4),
         upd("qwen", "Tongyi Qianwen broader public after clearance", 3),
         upd("autogen", "Microsoft AutoGen multi-agent framework heat", 3)],
        [ev("Mistral 7B", "Tiny EU lab punches above weight; HF downloads explode.",
            [], "2023-09-27")],
        [meme("7B战神", "Small model supremacy"),
         meme("DALL·E 3识字", "Text-in-image leap")],
        "Efficiency narrative; EU open lab celebrity; CN cloud ecosystems.",
        ["mistral-7b", "dalle-3", "meta-ai", "hunyuan", "qwen", "claude-2", "llama-2"],
    )
    MONTHS["2023-10"] = month_file(
        "2023-10",
        "Kimi long-context debut; agent winter after spring",
        [upd("kimi", "Moonshot Kimi closed beta / 128K context (Oct)", 5),
         upd("chatgpt", "Browse/voice feature churn continues", 3)],
        [ev("Kimi", "CN long-context branding becomes product differentiator.",
            ["https://en.wikipedia.org/wiki/Kimi_(AI)"])],
        [meme("能吞下一本书", "Context length flex"),
         meme("Agent回落", "AutoGPT hangover")],
        "Context length marketing battlefield; agents quieter.",
        ["kimi", "claude-2", "chatgpt", "mistral-7b", "perplexity"],
    )
    MONTHS["2023-11"] = month_file(
        "2023-11",
        "DevDay GPTs + GPT-4 Turbo + Grok-1 + Claude 2.1 + Yi + Amazon Q",
        [upd("gpt-4-turbo", "GPT-4 Turbo 128K (Nov 6)", 5),
         upd("gpts-custom", "Custom GPTs announced", 5),
         upd("grok-1", "xAI Grok-1 on X (Nov 4)", 4),
         upd("claude-2.1", "Claude 2.1 200K (Nov 21)", 4),
         upd("yi", "01.AI Yi open models", 4),
         upd("amazon-q", "Amazon Q preview (Nov 28)", 3),
         upd("deepseek-llm", "DeepSeek early open models visibility", 3),
         upd("inflection-2", "Inflection-2 claims", 2),
         upd("crewai", "CrewAI multi-agent framework rising", 2)],
        [ev("OpenAI DevDay", "GPTs, Assistants API, price cuts, 128K.",
            ["https://openai.com"], "2023-11-06"),
         ev("Grok-1", "xAI chatbot with 'maximum truth-seeking' branding.",
            [], "2023-11-04")],
        [meme("GPT商店幻想", "App Store for bots"),
         meme("Grok叛逆人设", "Anti-woke assistant jokes"),
         meme("零一万物", "Yi open weights")],
        "Platformization of chatbots; xAI meme energy; CN open labs multiply.",
        ["gpt-4-turbo", "gpts-custom", "grok-1", "claude-2.1", "yi", "amazon-q", "deepseek-llm", "kimi"],
    )
    MONTHS["2023-12"] = month_file(
        "2023-12",
        "Gemini 1.0 + Mixtral MoE + Phi-2 + Suno heat",
        [upd("gemini-1", "Google Gemini 1.0 (Dec 6)", 5),
         upd("mixtral", "Mixtral 8x7B open MoE (Dec 11)", 5),
         upd("phi-2", "Microsoft Phi-2", 3),
         upd("qwen", "Qwen 72B/1.8B downloadable releases", 3),
         upd("suno", "Suno AI music generation viral (Dec era)", 4)],
        [ev("Gemini launch", "Google unified multimodal flagship branding.",
            ["https://blog.google"], "2023-12-06"),
         ev("Mixtral", "Sparse MoE open model becomes default local choice.",
            [], "2023-12-11")],
        [meme("MoE复辟", "Experts are back"),
         meme("Gemini vs GPT-4", "Benchmark wars"),
         meme("Suno写歌", "AI music TikTok")],
        "Year closes with Google's answer + open MoE excitement + AI music.",
        ["gemini-1", "mixtral", "suno", "chatgpt", "claude-2.1", "qwen", "phi-2"],
    )

    # ===== 2024 =====
    MONTHS["2024-01"] = month_file(
        "2024-01",
        "Gemini Ultra path; StepFun; post-holiday tooling",
        [upd("gemini-1", "Gemini Ultra / Advanced rollout path", 3),
         upd("stepfun", "阶跃星辰 Step model public visibility (approx)", 3),
         upd("chatgpt", "GPT Store opens (Jan 10 reported)", 4)],
        [ev("GPT Store", "Custom GPTs store goes live for Plus users.",
            ["https://openai.com"])],
        [meme("年终总结都是AI写的", "Work ritual"),
         meme("GPT Store逛店", "Bot mall")],
        "Consolidation mood; waiting for next frontier drops.",
        ["chatgpt", "gpts-custom", "gemini-1", "claude-2.1", "stepfun", "mixtral"],
    )
    MONTHS["2024-02"] = month_file(
        "2024-02",
        "Gemini 1.5 Pro 1M + Gemma + Mistral Large + Sora demo",
        [upd("gemini-1.5", "Gemini 1.5 Pro long-context preview (Feb 15)", 5),
         upd("gemma", "Gemma 2B/7B open (Feb 21)", 4),
         upd("gemini-app", "Bard rebranded toward Gemini Advanced (Feb 8 Ultra path)", 4),
         upd("mistral-large", "Mistral Large API (Feb 26)", 4),
         upd("sora", "OpenAI Sora text-to-video research demo", 5),
         upd("qwen", "Qwen1.5 open family (Feb 4)", 3)],
        [ev("Sora", "Cinematic text-to-video demos redefine expectations.",
            ["https://openai.com"], "2024-02"),
         ev("1M context", "Needle-in-haystack demos go viral.",
            [], "2024-02-15")],
        [meme("海量上下文", "1M tokens flex"),
         meme("Sora物理学", "Beautiful but wrong physics"),
         meme("Gemma开源", "Google open small models")],
        "Context & video steal the show; EU open labs stay competitive.",
        ["gemini-1.5", "gemma", "sora", "mistral-large", "qwen", "chatgpt", "claude-2.1"],
    )
    MONTHS["2024-03"] = month_file(
        "2024-03",
        "Claude 3 family + Devin + Command R + Grok-1 open + OpenHands",
        [upd("claude-3", "Claude 3 Opus/Sonnet/Haiku (Mar 4–13)", 5),
         upd("devin", "Cognition Devin AI software engineer demo (Mar 12)", 5),
         upd("command-r", "Cohere Command R (Mar 24)", 3),
         upd("grok-1", "Grok-1 open-weight (Mar 17); Grok-1.5 (Mar 29)", 4),
         upd("openhands", "OpenDevin/OpenHands surge", 3)],
        [ev("Claude 3", "Opus claims frontier; vision + writing.",
            ["https://www.anthropic.com"], "2024-03-04"),
         ev("Devin", "Autonomous SWE narrative ignites.",
            ["https://cognition.ai/"], "2024-03-12")],
        [meme("Devin抢饭碗", "Jobs panic reprise"),
         meme("Claude三档", "Opus/Sonnet/Haiku menu"),
         meme("Grok开源权重", "xAI weights drop")],
        "Agentic coding hype returns; Claude fans declare a new favorite.",
        ["claude-3", "devin", "command-r", "grok-1", "openhands", "gpt-4", "cursor"],
    )
    MONTHS["2024-04"] = month_file(
        "2024-04",
        "Llama 3 + Phi-3 + Command R+ + Mixtral 8x22B + Amazon Q GA",
        [upd("llama-3", "Llama 3 8B/70B (Apr 18)", 5),
         upd("phi-3", "Phi-3 mini/medium", 4),
         upd("command-r", "Command R+ (Apr 4)", 3),
         upd("mixtral", "Mixtral 8x22B (Apr 10)", 3),
         upd("minimax", "abab6.5 / 6.5s (Apr 17)", 3),
         upd("amazon-q", "Amazon Q GA (Apr 30)", 3),
         upd("swe-agent", "SWE-agent academic agent", 2),
         upd("udio", "Udio music rival heat", 3)],
        [ev("Llama 3", "Quality jump; community fine-tunes flood HF.",
            [], "2024-04-18")],
        [meme("Llama3本地党", "Home lab renaissance"),
         meme("Phi-3小钢炮", "Tiny but mighty")],
        "Open models feel newly close to GPT-4-class for many tasks.",
        ["llama-3", "phi-3", "command-r", "minimax", "amazon-q", "claude-3", "udio"],
    )
    MONTHS["2024-05"] = month_file(
        "2024-05",
        "GPT-4o + Gemini 1.5 Flash + DeepSeek-V2 + Codestral + Veo tease",
        [upd("gpt-4o", "GPT-4o omni voice/vision (May 13)", 5),
         upd("gemini-1.5", "Gemini 1.5 Flash (May 14)", 4),
         upd("deepseek-v2", "DeepSeek-V2 open MoE (May 7)", 4),
         upd("mistral-large", "Codestral 22B coding model (May 29) via Mistral line", 3),
         upd("veo", "Google Veo video model announced at I/O", 3),
         upd("copilot-workspace", "Copilot Workspace agentic IDE experiments", 2)],
        [ev("GPT-4o", "Realtime voice demos; Scarlett Johansson controversy soon after.",
            ["https://openai.com"], "2024-05-13")],
        [meme("Her语音", "Scarlett / Her vibes controversy"),
         meme("4o免费层", "Frontier in free tier"),
         meme("DeepSeek性价比", "CN efficiency legend starts")],
        "Multimodal realtime feels magical; CN efficiency labs noticed globally.",
        ["gpt-4o", "gemini-1.5", "deepseek-v2", "claude-3", "cursor", "veo"],
    )
    MONTHS["2024-06"] = month_file(
        "2024-06",
        "Claude 3.5 Sonnet + Qwen2 + Apple Intelligence + Gemma 2 + Kling",
        [upd("claude-3.5-sonnet", "Claude 3.5 Sonnet (Jun 20)", 5),
         upd("qwen", "Qwen2 open family (Jun 7)", 4),
         upd("apple-intelligence", "Apple Intelligence at WWDC", 5),
         upd("gemma", "Gemma 2 (Jun 27)", 3),
         upd("deepseek-coder", "DeepSeek-Coder-V2 (Jun 17)", 3),
         upd("kling", "可灵 Kling video (Jun)", 3),
         upd("luma-dream-machine", "Luma Dream Machine video", 3)],
        [ev("WWDC Apple Intelligence", "On-device + Private Cloud Compute narrative.",
            [], "2024-06"),
         ev("Claude 3.5 Sonnet", "Coding/writing leap; Artifacts era begins soon after.",
            ["https://www.anthropic.com"], "2024-06-20")],
        [meme("Artifacts", "Side-panel apps from chat"),
         meme("苹果隐私AI", "Not-training-on-you flex"),
         meme("可灵", "CN video gen")],
        "Sonnet becomes default workhorse; Apple legitimizes consumer AI.",
        ["claude-3.5-sonnet", "qwen", "apple-intelligence", "gemma", "gpt-4o", "kling"],
    )
    MONTHS["2024-07"] = month_file(
        "2024-07",
        "Llama 3.1 405B + GPT-4o mini + Mistral Large 2",
        [upd("llama-3.1", "Llama 3.1 8B/70B/405B (Jul 23)", 5),
         upd("gpt-4o-mini", "GPT-4o mini (Jul 18)", 4),
         upd("mistral-large-2", "Mistral Large 2 (Jul 24)", 3),
         upd("kimi", "Kimi context caching public beta", 3)],
        [ev("Llama 3.1 405B", "Largest open-ish frontier-class release of the summer.",
            [], "2024-07-23")],
        [meme("405B下载焦虑", "Disk space memes"),
         meme("4o-mini取代3.5", "Cheap default swap")],
        "Open frontier scale feels real; cheap GPT tier reshapes apps.",
        ["llama-3.1", "gpt-4o-mini", "mistral-large-2", "claude-3.5-sonnet", "kimi"],
    )
    MONTHS["2024-08"] = month_file(
        "2024-08",
        "Grok-2 + Qwen2-VL/Audio + Cursor Composer culture",
        [upd("grok-2", "Grok-2 / mini (Aug 13)", 4),
         upd("qwen", "Qwen2-VL / Audio / Math wave", 4),
         upd("cursor", "Cursor Composer / Tab culture peak", 4),
         upd("cursor-composer", "Composer multi-file edits mainstreamed", 4),
         upd("command-r", "Command R Aug-2024 refresh", 2)],
        [ev("Grok-2", "xAI pushes realtime X integration identity.",
            [], "2024-08-13")],
        [meme("Cursor Tab信仰", "Accept-all autocomplete religion"),
         meme("Qwen多模态雨", "Open VL flood")],
        "IDE agents normalize; multimodal open models stack up.",
        ["grok-2", "qwen", "cursor", "cursor-composer", "claude-3.5-sonnet", "gpt-4o"],
    )
    MONTHS["2024-09"] = month_file(
        "2024-09",
        "o1-preview reasoning + Llama 3.2 + Qwen2.5 + Pixtral",
        [upd("o1", "o1-preview + o1-mini (Sep 12)", 5),
         upd("llama-3.2", "Llama 3.2 multimodal/edge (Sep 25)", 4),
         upd("qwen", "Qwen2.5 + Math (Sep 19)", 4),
         upd("pixtral", "Mistral Pixtral 12B (Sep 11)", 3),
         upd("deepseek-v2.5", "DeepSeek-V2.5 (Sep 5)", 2)],
        [ev("o1 reasoning models", "Hidden chain-of-thought; thinking product category born.",
            ["https://openai.com"], "2024-09-12")],
        [meme("它在思考", "Loading animation as product"),
         meme("草莓计划", "Strawberry rumors made real")],
        "Reasoning-time compute becomes the new scaling story.",
        ["o1", "llama-3.2", "qwen", "pixtral", "claude-3.5-sonnet"],
    )
    MONTHS["2024-10"] = month_file(
        "2024-10",
        "Claude 3.5 Sonnet (new) + Computer Use + Kimi Explore",
        [upd("claude-3.5-sonnet", "Claude 3.5 Sonnet upgraded (Oct 22)", 5),
         upd("claude-computer-use", "Computer Use public beta", 5),
         upd("claude-3.5-haiku", "Haiku 3.5 path (Nov spillover; Oct prep)", 2),
         upd("kimi", "Kimi Explore Edition (Oct 11)", 3)],
        [ev("Computer Use", "Claude controls mouse/keyboard — agent demos galore.",
            ["https://www.anthropic.com"], "2024-10")],
        [meme("AI点鼠标", "GUI agent wow + fail compilations"),
         meme("Computer Use翻车", "Clicking wrong buttons ASMR")],
        "GUI agents feel newly real; excitement + safety anxiety.",
        ["claude-3.5-sonnet", "claude-computer-use", "kimi", "o1", "cursor", "devin"],
    )
    MONTHS["2024-11"] = month_file(
        "2024-11",
        "Claude 3.5 Haiku + Qwen2.5-Coder + QwQ + MCP",
        [upd("claude-3.5-haiku", "Claude 3.5 Haiku (Nov 4)", 3),
         upd("qwen", "Qwen2.5-Coder-32B (Nov 12); QwQ-32B-Preview (Nov 28)", 4),
         upd("pixtral", "Pixtral Large (Nov 18)", 3),
         upd("mcp", "Model Context Protocol announced", 4)],
        [ev("MCP", "Anthropic open protocol for tool/context wiring.",
            [], "2024-11"),
         ev("QwQ preview", "Open reasoning follows o1 narrative.",
            [], "2024-11-28")],
        [meme("开源也要think", "Open reasoning race"),
         meme("MCP插头", "USB-C for tools meme")],
        "Coding + reasoning open models; protocol layer appears.",
        ["claude-3.5-haiku", "qwen", "mcp", "pixtral", "o1"],
    )
    MONTHS["2024-12"] = month_file(
        "2024-12",
        "DeepSeek-V3 + Gemini 2.0 + o1 GA + Llama 3.3 + Sora public",
        [upd("deepseek-v3", "DeepSeek-V3 671B MoE (Dec 26)", 5),
         upd("gemini-2", "Gemini 2.0 Flash (Dec 11); Thinking exp (Dec 19)", 5),
         upd("o1", "o1 full + ChatGPT Pro (Dec 5)", 5),
         upd("llama-3.3", "Llama 3.3 70B (Dec 6)", 4),
         upd("sora", "Sora Turbo public access (Dec 9)", 4),
         upd("phi-4", "Phi-4", 3)],
        [ev("DeepSeek-V3", "Frontier-ish quality at startling training-cost narrative.",
            [], "2024-12-26")],
        [meme("V3性价比核弹", "Cost shock"),
         meme("ChatGPT Pro 200刀", "Pro tier sticker shock"),
         meme("Gemini 2.0 agentic", "Google agents")],
        "Year-end plot twist: CN open MoE + Google agents + paid Pro tiers.",
        ["deepseek-v3", "gemini-2", "o1", "llama-3.3", "sora", "phi-4", "claude-3.5-sonnet"],
    )

    # ===== 2025 =====
    MONTHS["2025-01"] = month_file(
        "2025-01",
        "DeepSeek-R1 + Operator + o3-mini + Kimi K1.5",
        [upd("deepseek-r1", "DeepSeek-R1 open reasoning (Jan 20)", 5),
         upd("operator", "OpenAI Operator preview (Jan 23)", 5),
         upd("o3", "o3-mini (Jan 31)", 4),
         upd("kimi", "Kimi K1.5 reasoning (Jan 20)", 4),
         upd("minimax", "MiniMax-Text-01 / VL-01 (Jan 15)", 3),
         upd("gemini-2", "Gemini 2.0 Flash GA (Jan 30)", 3),
         upd("qwen", "Qwen2.5-VL / 1M / Max late-Jan wave", 4)],
        [ev("R1 moment", "Open reasoning goes viral; API cost wars intensify.",
            [], "2025-01-20"),
         ev("Operator", "Computer-use agent in ChatGPT ecosystem.",
            ["https://openai.com"], "2025-01-23")],
        [meme("R1蒸馏全家桶", "Distill everything"),
         meme("DeepSeek挤爆", "Servers melt"),
         meme("Operator订餐", "Agent does chores")],
        "Open reasoning worldwide; CN models hit Western timelines hard.",
        ["deepseek-r1", "operator", "o3", "kimi", "minimax", "qwen", "chatgpt"],
    )
    MONTHS["2025-02"] = month_file(
        "2025-02",
        "Claude 3.7 + Claude Code + Grok 3 + GPT-4.5",
        [upd("claude-3.7-sonnet", "Claude 3.7 Sonnet hybrid reasoning (Feb 24)", 5),
         upd("claude-code", "Claude Code research preview (Feb 24)", 5),
         upd("grok-3", "Grok 3 / mini (Feb 17)", 4),
         upd("gpt-4.5", "GPT-4.5 research preview (Feb 27)", 4),
         upd("gemini-2", "Gemini 2.0 Pro experimental (Feb 5)", 3)],
        [ev("Claude Code + 3.7", "Terminal agent + hybrid thinking same day.",
            ["https://www.anthropic.com"], "2025-02-24")],
        [meme("Claude Code接管仓库", "Agentic IDE CLI"),
         meme("Grok3直播", "Launch spectacle"),
         meme("GPT-4.5人味", "Personality claims")],
        "Coding agents leave chat boxes; labs ship personality + reason.",
        ["claude-3.7-sonnet", "claude-code", "grok-3", "gpt-4.5", "cursor", "deepseek-r1"],
    )
    MONTHS["2025-03"] = month_file(
        "2025-03",
        "Manus agent + Gemini 2.5 Pro + Gemma 3 + QwQ-32B",
        [upd("manus", "Manus invite-only general agent (Mar 6)", 5),
         upd("gemini-2.5", "Gemini 2.5 Pro experimental (Mar 25)", 5),
         upd("gemma", "Gemma 3 multimodal open (Mar 12)", 3),
         upd("qwen", "QwQ-32B + Omni / QVQ-Max", 4),
         upd("deepseek-v3", "DeepSeek-V3-0324 update", 3),
         upd("command-r", "Command A (Mar 13)", 2)],
        [ev("Manus launch", "CN general agent demo culture peaks.",
            ["https://www.scriptbyai.com/manus-ai-timeline/"], "2025-03-06")],
        [meme("Manus邀请码", "Invite scarcity status"),
         meme("Gemini2.5刷榜", "Leaderboard flex")],
        "General agents + thinking models; invite codes as status.",
        ["manus", "gemini-2.5", "gemma", "qwen", "claude-code", "deepseek-r1"],
    )
    MONTHS["2025-04"] = month_file(
        "2025-04",
        "Llama 4 + o3/o4-mini + GPT-4.1 + Qwen3 + Codex CLI",
        [upd("llama-4", "Llama 4 Scout/Maverick (Apr 5)", 5),
         upd("o3", "o3 + o4-mini (Apr 16)", 5),
         upd("gpt-4.1", "GPT-4.1 / mini / nano (Apr 14)", 4),
         upd("qwen", "Qwen3 hybrid reasoning (Apr 29)", 5),
         upd("codex-agent", "OpenAI Codex CLI (Apr 16)", 4),
         upd("kimi", "Kimi-VL (Apr 10)", 3),
         upd("gemini-2.5", "Gemini 2.5 Flash (Apr 17)", 3)],
        [ev("Llama 4", "Open multimodal MoE; huge context claims.",
            [], "2025-04-05")],
        [meme("Scout/Maverick起名", "Western movie model names"),
         meme("Qwen3 think开关", "Hybrid reasoning modes")],
        "Reasoning APIs + open MoE multimodal; coding CLIs proliferate.",
        ["llama-4", "o3", "gpt-4.1", "qwen", "codex-agent", "kimi", "claude-code"],
    )
    MONTHS["2025-05"] = month_file(
        "2025-05",
        "Claude 4 + Claude Code GA + Codex cloud + Manus public",
        [upd("claude-4", "Claude Opus 4 / Sonnet 4 (May 22)", 5),
         upd("claude-code", "Claude Code GA (May 22)", 5),
         upd("codex-agent", "Codex cloud agent in ChatGPT (May 16)", 4),
         upd("manus", "Manus public registration (May 13)", 3),
         upd("deepseek-r1", "R1-0528 update", 3)],
        [ev("Code with Claude", "Opus/Sonnet 4 + Claude Code GA.",
            [], "2025-05-22")],
        [meme("Claude4编码王座", "SWE-bench crown fight"),
         meme("Codex vs Claude Code", "Camp wars")],
        "Agentic coding products go GA; labs race SWE narratives.",
        ["claude-4", "claude-code", "codex-agent", "manus", "cursor", "devin"],
    )
    MONTHS["2025-06"] = month_file(
        "2025-06",
        "o3-pro + Magistral + MiniMax-M1 + Kimi-Dev",
        [upd("o3", "o3-pro (Jun 10)", 4),
         upd("minimax", "MiniMax-M1 (Jun 16)", 3),
         upd("kimi", "Kimi-Dev-72B + VL-Thinking", 4),
         upd("apple-intelligence", "Broader Apple Intelligence rollouts", 2)],
        [ev("Open coding specialists", "Kimi-Dev and peers push SWE open models.",
            [])],
        [meme("开源Dev刷SWE", "Benchmark grinding"),
         meme("o3-pro烧钱", "Think harder for $$$")],
        "Specialist open models; pro reasoning tiers for power users.",
        ["o3", "kimi", "minimax", "claude-4", "codex-agent"],
    )
    MONTHS["2025-07"] = month_file(
        "2025-07",
        "Grok 4 + Kimi K2 + ChatGPT agent + Qwen3-Coder",
        [upd("grok-4", "Grok 4 (Jul 9)", 5),
         upd("kimi", "Kimi K2 agentic MoE (Jul 11)", 5),
         upd("chatgpt-agent", "ChatGPT agent unifies Operator + deep research (Jul 17)", 4),
         upd("qwen", "Qwen3-Coder (Jul 22)", 4)],
        [ev("Kimi K2", "Trillion-scale MoE open-weight agent narrative.",
            [], "2025-07-11")],
        [meme("K2开放权重狂欢", "HF stampede"),
         meme("ChatGPT agent一键干活", "Do-my-job button")],
        "Agents productized inside chat UIs; open MoE scale wars.",
        ["grok-4", "kimi", "chatgpt-agent", "qwen", "claude-code", "operator"],
    )
    MONTHS["2025-08"] = month_file(
        "2025-08",
        "GPT-5 + Claude Opus 4.1 + DeepSeek-V3.1",
        [upd("gpt-5", "GPT-5 family + mini/nano (Aug 7)", 5),
         upd("claude-opus-4.1", "Claude Opus 4.1 (Aug 5)", 4),
         upd("deepseek-v3.1", "DeepSeek-V3.1 (Aug 21)", 3),
         upd("grok-4", "Grok Code Fast 1 (Aug 28)", 3),
         upd("qwen", "Qwen-Image (Aug 4)", 2)],
        [ev("GPT-5 launch", "Mainline generation jump.",
            ["https://openai.com"], "2025-08-07")],
        [meme("GPT-5终于来了", "Long-awaited number bump"),
         meme("夏日模型雨", "Release fatigue")],
        "Flagship reset month; open and closed both loud.",
        ["gpt-5", "claude-opus-4.1", "deepseek-v3.1", "grok-4", "cursor"],
    )
    MONTHS["2025-09"] = month_file(
        "2025-09",
        "Claude Sonnet 4.5 + Qwen3-Omni/VL + Grok 4 Fast",
        [upd("claude-sonnet-4.5", "Claude Sonnet 4.5 (Sep 29)", 5),
         upd("deepseek-v3.2", "DeepSeek-V3.2-Exp (Sep 29)", 3),
         upd("qwen", "Qwen3-Omni + Qwen3-VL", 4),
         upd("grok-4", "Grok 4 Fast (Sep 19)", 3),
         upd("kimi", "OK Computer agentic feature reporting", 3)],
        [ev("Sonnet 4.5", "Balanced agent/coding workhorse upgrade.",
            [], "2025-09-29")],
        [meme("默认模型又换了", "Upgrade treadmill"),
         meme("OK Computer", "Kimi agent mode")],
        "Workhorse upgrades; multimodal open stacks mature.",
        ["claude-sonnet-4.5", "qwen", "deepseek-v3.2", "grok-4", "kimi", "gpt-5"],
    )
    MONTHS["2025-10"] = month_file(
        "2025-10",
        "Claude Haiku 4.5 + Codex GA + MiniMax-M2 + Composer model",
        [upd("claude-haiku-4.5", "Claude Haiku 4.5 (Oct 15)", 3),
         upd("codex-agent", "Codex generally available (Oct 6)", 4),
         upd("minimax", "MiniMax-M2 (Oct 27)", 3),
         upd("kimi", "Kimi Linear (Oct 30)", 3),
         upd("composer-model", "Cursor Composer model line visibility", 3)],
        [ev("Codex GA", "Cloud coding agent leaves preview.",
            ["https://openai.com"], "2025-10-06")],
        [meme("Codex转正", "Agent graduation"),
         meme("Haiku又快又香", "Cheap fast tier")],
        "Agents graduate; fast cheap tiers keep apps snappy.",
        ["claude-haiku-4.5", "codex-agent", "minimax", "kimi", "composer-model", "cursor"],
    )
    MONTHS["2025-11"] = month_file(
        "2025-11",
        "Gemini 3 + GPT-5.1 + Claude Opus 4.5 + Grok 4.1 + OpenClaw",
        [upd("gemini-3", "Gemini 3 flagship (Nov 18)", 5),
         upd("gpt-5.1", "GPT-5.1 Instant/Thinking/Codex-Mini (Nov 12–19)", 5),
         upd("claude-opus-4.5", "Claude Opus 4.5 (Nov 24)", 5),
         upd("grok-4.1", "Grok 4.1 (Nov 17)", 3),
         upd("kimi", "Kimi K2 Thinking (Nov 6)", 4),
         upd("openclaw", "OpenClaw self-hosted agent gateway heat", 3),
         upd("grok-bot", "Grok Bot teammate framing in discourse", 3)],
        [ev("Triple flagship week", "Google/OpenAI/Anthropic major bumps.",
            [])],
        [meme("三强同台", "Same-week launches"),
         meme("Thinking标配化", "Everyone thinks now"),
         meme("OpenClaw龙虾", "Lobster agent gateway")],
        "Frontier cadence feels weekly; users exhausted but upgrading.",
        ["gemini-3", "gpt-5.1", "claude-opus-4.5", "grok-4.1", "kimi", "openclaw", "grok-bot"],
    )
    MONTHS["2025-12"] = month_file(
        "2025-12",
        "GPT-5.2 + Gemini 3 Flash + DeepSeek-V3.2 + Manus↔Meta news",
        [upd("gpt-5.2", "GPT-5.2 + Codex variant (Dec 11–18)", 5),
         upd("gemini-3", "Gemini 3 Flash (Dec 17)", 4),
         upd("deepseek-v3.2", "DeepSeek-V3.2 (Dec 1)", 4),
         upd("mistral-large", "Mistral Large 3 / Devstral 2 (Dec)", 3),
         upd("minimax", "MiniMax-M2.1 (Dec 23)", 2),
         upd("manus", "Manus announces joining Meta (Dec 29)", 4)],
        [ev("Manus-Meta deal news", "Agent startup joins Meta; independence drama later in 2026.",
            [], "2025-12-29")],
        [meme("年终旗舰清仓", "December dump"),
         meme("Manus并入Meta", "M&A popcorn")],
        "Year-end mega-updates; M&A in agent space.",
        ["gpt-5.2", "gemini-3", "deepseek-v3.2", "manus", "claude-opus-4.5"],
    )

    # ===== 2026 =====
    MONTHS["2026-01"] = month_file(
        "2026-01",
        "Kimi K2.5 multimodal agents; post-holiday digest",
        [upd("kimi", "Kimi K2.5 open multimodal agentic (Jan 27)", 4)],
        [ev("Agent swarm narratives", "Multi-agent open models become discourse center.",
            [])],
        [meme("子代理成群", "Swarm memes"),
         meme("新年第一卷", "AI-written OKRs")],
        "Builders digest 2025 flagships; CN open agents loud.",
        ["kimi", "gpt-5.2", "claude-opus-4.5", "openclaw", "cursor"],
    )
    MONTHS["2026-02"] = month_file(
        "2026-02",
        "Claude 4.6 + GPT-5.3-Codex + Qwen3.5 + Gemini 3.1 + Grok 4.20",
        [upd("claude-opus-4.6", "Claude Opus 4.6 (Feb 5)", 5),
         upd("claude-sonnet-4.6", "Claude Sonnet 4.6 (Feb 17)", 4),
         upd("gpt-5.3-codex", "GPT-5.3-Codex (Feb 5)", 4),
         upd("qwen", "Qwen3.5 + Plus (Feb 16)", 4),
         upd("gemini-3.1", "Gemini 3.1 Pro preview (Feb 19)", 4),
         upd("grok-4", "Grok 4.20 (Feb 17) — track as grok-4 line", 3),
         upd("minimax", "MiniMax-M2.5 (Feb 12)", 3)],
        [ev("Early-year frontier refresh", "Anthropic/OpenAI/Google/Qwen all move.",
            [])],
        [meme("版本号小数点战争", "x.y inflation"),
         meme("Nano Banana", "Gemini image nickname lore")],
        "Cadence fatigue real; still upgrading defaults.",
        ["claude-opus-4.6", "claude-sonnet-4.6", "gpt-5.3-codex", "qwen", "gemini-3.1", "minimax"],
    )
    MONTHS["2026-03"] = month_file(
        "2026-03",
        "GPT-5.4 native computer-use + MiniMax-M2.7 + Qwen3.5-Omni",
        [upd("gpt-5.4", "GPT-5.4 native computer-use (Mar 3–17)", 5),
         upd("minimax", "MiniMax-M2.7 (Mar 18)", 3),
         upd("qwen", "Qwen3.5-Omni (Mar 30)", 3),
         upd("gemini-3", "Gemini 3.1 Flash-Lite (Mar 3)", 2)],
        [ev("Native computer use in mainline GPT", "Agents baked into frontier chat models.",
            [], "2026-03-05")],
        [meme("电脑操作不再是彩蛋", "Computer use expected"),
         meme("Omni一把梭", "All modalities")],
        "Computer-use becomes expected, not demo-only.",
        ["gpt-5.4", "minimax", "qwen", "claude-opus-4.6", "operator", "claude-computer-use"],
    )
    MONTHS["2026-04"] = month_file(
        "2026-04",
        "GPT-5.5 + DeepSeek-V4 + Claude Mythos/Opus 4.7 + Kimi K2.6 + Muse Spark",
        [upd("gpt-5.5", "GPT-5.5 (Apr 23)", 5),
         upd("deepseek-v4", "DeepSeek-V4 Pro/Flash open weights (Apr 24)", 5),
         upd("claude-fable-5", "Claude Mythos Preview (Apr 7) — restricted", 4),
         upd("claude-opus-4.7", "Claude Opus 4.7 (Apr 16)", 4),
         upd("kimi", "Kimi K2.6 (Apr 20)", 4),
         upd("muse-spark", "Meta Muse Spark (Apr 8)", 3),
         upd("gemma", "Gemma 4 (Apr 2)", 3),
         upd("qwen", "Qwen3.6-Plus (Apr 2)", 3)],
        [ev("DeepSeek-V4", "Next efficiency frontier claim with open weights.",
            [], "2026-04-24")],
        [meme("V4又来砸场", "DeepSeek sequel"),
         meme("Mythos限制访问", "Restricted model lore"),
         meme("Muse Spark", "Meta coding/reasoning")],
        "Open CN vs closed US narrative reignites; restricted models intrigue.",
        ["gpt-5.5", "deepseek-v4", "claude-fable-5", "claude-opus-4.7", "kimi", "muse-spark"],
    )
    MONTHS["2026-05"] = month_file(
        "2026-05",
        "Claude Opus 4.8 + Gemini 3.5 Flash + Qwen3.7-Max + Grok 4.3",
        [upd("claude-opus-4.8", "Claude Opus 4.8 (May 28)", 5),
         upd("gemini-3", "Gemini 3.5 Flash GA (May 19)", 4),
         upd("qwen", "Qwen3.7-Max (May 20)", 4),
         upd("grok-4", "Grok 4.3 (May 6); Grok Build 0.1 (May 19)", 3),
         upd("gpt-5.5", "GPT-5.5 Instant + Realtime-2 family", 3)],
        [ev("Mid-2026 workhorse upgrades", "Flash/Max/Opus lanes refresh.",
            [])],
        [meme("Flash性价比永动机", "Fast tier forever"),
         meme("Grok Build", "Coding agent from xAI")],
        "Production models prioritized over pure wow demos.",
        ["claude-opus-4.8", "gemini-3", "qwen", "grok-4", "gpt-5.5"],
    )
    MONTHS["2026-06"] = month_file(
        "2026-06",
        "Claude Fable/Mythos 5 + GLM-5.2 + MiniMax M3 + access drama",
        [upd("claude-fable-5", "Claude Fable 5 + Mythos 5 (Jun 9); access drama ~Jun 12", 5),
         upd("claude-sonnet-5", "Claude Sonnet 5 line reporting", 3),
         upd("chatglm", "Z.ai GLM-5.2 open coding/agentic (Jun 13–16)", 5),
         upd("minimax", "MiniMax M3 (Jun 1)", 3),
         upd("gemma", "Gemma 4 12B (Jun 3)", 2),
         upd("gpt-5.6", "GPT-5.6 prep/early mentions (full GA Jul)", 2)],
        [ev("Fable/Mythos access suspension reporting", "Export-control/access drama — verify primary sources.",
            ["https://axis-intelligence.com/ai-model-release-tracker/"], "2026-06-12"),
         ev("GLM-5.2 open weights", "CN open coding model claims arena tops.",
            [], "2026-06-16")],
        [meme("Fable上线又下线", "Availability politics"),
         meme("GLM开源编码刷榜", "CN coding crown")],
        "Capability vs availability politics; open CN coding surge.",
        ["claude-fable-5", "chatglm", "minimax", "claude-sonnet-5", "deepseek-v4"],
    )
    MONTHS["2026-07"] = month_file(
        "2026-07",
        "GPT-5.6 Sol/Terra/Luna + Claude Opus 5 + Kimi K3 + DeepSeek-V4-Flash-0731",
        [upd("gpt-5.6", "GPT-5.6 Sol/Terra/Luna GA (Jul 9); price cuts Jul 30", 5),
         upd("claude-opus-5", "Claude Opus 5 (Jul 24)", 5),
         upd("claude-fable-5", "Fable 5 redeploy reporting (Jul 1)", 3),
         upd("kimi", "Kimi K3 2.8T (Jul 16); weights ~Jul 27", 5),
         upd("deepseek-v4", "DeepSeek-V4-Flash-0731 (Jul 31)", 4),
         upd("qwen", "Qwen3.8 preview at WAIC (Jul 19)", 3),
         upd("gemini-3", "Gemini 3.6 Flash + 3.5 Flash-Lite GA (Jul 21)", 4),
         upd("muse-spark", "Muse Spark 1.1 (Jul 9)", 2),
         upd("doubao", "Doubao Seedance / Seed 2.1 updates", 3),
         upd("grok-4.5", "Grok 4.5 line visibility", 3)],
        [ev("Summer 2026 frontier cluster", "US+CN labs ship within weeks; WAIC energy.",
            [])],
        [meme("Sol/Terra/Luna行星命名", "OpenAI planet trio"),
         meme("K3两兆参数", "Parameter flex"),
         meme("Opus5编码王冠", "Coding crown posts")],
        "Peak release density; benchmarks and price cuts dominate feeds.",
        ["gpt-5.6", "claude-opus-5", "kimi", "deepseek-v4", "gemini-3", "qwen", "doubao", "grok-4.5"],
    )
    MONTHS["2026-08"] = month_file(
        "2026-08",
        "Qwen3.8-Max + Grok 4.6 + Muse Spark 1.2 + Manus independence",
        [upd("qwen", "Qwen3.8-Max GA (~Aug 2–3); open weights ~Aug 12", 5),
         upd("grok-4.6", "Grok 4.6 (~Aug 12)", 4),
         upd("muse-spark", "Muse Spark 1.2 (Aug 5)", 3),
         upd("chatglm", "GLM-5.3 reporting mid-Aug", 3),
         upd("manus", "Return to independent operation (Aug 11)", 3),
         upd("hunyuan", "Tencent Hy4 Preview open-weight reporting", 3)],
        [ev("Qwen3.8-Max", "Alibaba flagship cloud + partial open weights.",
            [], "2026-08-03"),
         ev("Manus independence", "Reversal of Meta joining narrative.",
            [], "2026-08-11")],
        [meme("通义3.8对线K3", "CN flagship duel"),
         meme("Manus独立反转", "Corporate soap opera")],
        "CN flagship open/cloud dual track; corporate agent drama.",
        ["qwen", "grok-4.6", "muse-spark", "chatglm", "manus", "hunyuan", "kimi"],
    )
    MONTHS["2026-09"] = month_file(
        "2026-09",
        "DB cutoff: post-summer normalization (refresh before chapter)",
        [upd("gpt-6-astra", "GPT-6 Astra reporting — UNCERTAIN secondary trackers", 3),
         upd("gpt-5.6", "GPT-5.6 family still widely discussed as current line", 2),
         upd("claude-opus-5", "Claude Opus 5 / Fable line remain discourse leaders", 2),
         upd("qwen", "Qwen3.8 generation still rolling out variants", 2),
         upd("kimi", "Kimi K3 ecosystem adoption", 2),
         upd("deepseek-v4", "DeepSeek-V4 Flash/Pro serving iterations", 2)],
        [ev("DB coverage end", "Append new releases after this snapshot; verify Sep 2026 primaries before chapter canon.",
            [])],
        [meme("又要换默认模型吗", "Upgrade fatigue"),
         meme("开源大餐后的部署现实", "VRAM economics")],
        "Normalization after summer flood; cost/latency/agents > raw params.",
        ["gpt-5.6", "gpt-6-astra", "claude-opus-5", "qwen", "kimi", "deepseek-v4", "gemini-3",
         "cursor", "claude-code", "codex-agent", "openclaw", "grok-bot"],
    )
    return MONTHS
